import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  viewStyle: {
    backgroundColor: "white",
    flex: 1,
    //justifyContent:"space-between",
    //padding: 5,
    //marginTop: 100,
  },
  TitleContainer: {
    justifyContent: "center",
    borderWidth: 1,
    height: 40,
    width: "100%",
    borderColor: "#817E7E",
    backgroundColor: "#C597FF",
    //marginTop:100,
    textAlign: "center",
    marginBottom: 30,
  },
  textInput: {
    color: "#000000",
    borderBottomWidth: 1,
    marginBottom: 25,
    height: 45,
    fontSize: 15,
    borderWidth: 1,
    width: "90%",
    borderColor: "#817E7E",
    marginTop: 5,
    borderRadius: 5,
    backgroundColor: "#ECECEC",
    justifyContent: "center",
    padding: 5,
  },
  inputContainer: {
    //marginTop: 50,
    flexDirection: "column",
    justifyContent: "space-between",
    paddingLeft: 30,
  },
  registrationInputContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 5,
  },
  registrationInput: {
    fontSize: 15,
    borderWidth: 1,
    borderColor: "#817E7E",
    width: "47%",
    height: 45,
    borderRadius: 5,
    marginBottom: 5,
    backgroundColor: "#ECECEC",
    paddingLeft: 5,
  },
  loginButtonContainer: {
    marginTop: 30,
    justifyContent: "center",
    alignItems: "center",
    height: 45,
    width: 135,
    borderWidth: 1,
    borderColor: "#000000",
    backgroundColor: "#C597FF",
    marginLeft: 120,
    borderRadius: 30,
  },
  loginButtonText: {
    fontSize: 17,
    //fontWeight: 'bold'
  },
  signUpText: {
    //used in login
    marginTop: 35,
    fontSize: 16,
    color: "#00B2FF",
    justifyContent: "center",
    alignItems: "center",
    width: 170,
    marginLeft: 115,
  },
  orText: {
    //used in login
    textAlign: "center",
    marginTop: 35,
    fontSize: 15,
    color: "#000000",
    width: 30,
    marginLeft: 170,
    borderColor: "#817E7E",
    borderWidth: 1,
    borderRadius: 4,
  },
  titleContainer: {
    //marginTop:30,
    justifyContent: "center",
    alignItems: "center",
    height: 60,
    width: 135,
    borderWidth: 1,
    borderColor: "#000000",
    backgroundColor: "#C597FF",
    //marginLeft: 110,
    //borderRadius: 30
  },
  latestTransactionContainer: {
    marginTop: 60,
    justifyContent: "center",
    textAlign: "left",
    height: 50,
    width: "100%",
    borderWidth: 1,
    borderColor: "#000000",
    backgroundColor: "#C597FF",
  },
  DatetransactionContainer: {
    //marginTop:150,
    justifyContent: "center",
    textAlign: "left",
    height: 40,
    width: "100%",
    borderWidth: 1,
    borderColor: "#000000",
    backgroundColor: "#E9E9E9",
  },
  transactionContainer: {
    flexDirection: "row",
    //justifyContent:'center',
    textAlign: "left",
    height: 60,
    width: "100%",
    borderWidth: 1,
    borderColor: "#000000",
    backgroundColor: "white",
  },
  editProfileText: {
    marginTop: 30,
    fontSize: 11,
    color: "black",
    justifyContent: "center",
    textAlign: "center",
    width: 75,
    //borderWidth: 1,
  },
  userProfileName: {
    marginTop: 50,
    fontSize: 20,
    color: "black",
    textAlign: "center",
    width: "100%",
    //borderWidth: 1,
  },
  imageBox: {
    flexDirection: "row",
    justifyContent: "center",
  },
  image_editContainer: {
    height: 17,
    borderColor: "#817E7E",
    //marginTop: 30,
  },
  BackContainer: {
    borderwidth: 1,
    height: 45,
    width: 45,
    borderColor: "#C597FF",
    //backgroundColor:"blue",
    marginRight: 325,
    marginTop: 40,
  },
  ProfileBackContainer: {
    borderwidth: 1,
    height: 45,
    width: 45,
    borderColor: "#C597FF",
    //backgroundColor:"blue",
    //marginTop:5
  },
  backArrowContainer: {
    height: 35,
    width: 35,
    borderColor: "#C597FF",
    //backgroundColor:"blue",
    marginTop: 40,
    marginLeft: 5,
  },
  Cartitems: {
    flexDirection: "row",
    //justifyContent:'center',
    textAlign: "left",
    padding: 5,
    height: 75,
    width: 375,
    borderWidth: 1,
    borderColor: "#000000",
    backgroundColor: "white",
    marginLeft: 10,
  },
  ScannedItemsHeader: {
    marginTop: 10,
    justifyContent: "center",
    textAlign: "left",
    height: 30,
    width: 375,
    borderWidth: 1,
    borderColor: "#000000",
    backgroundColor: "#C597FF",
    marginLeft: 10,
  },
  PlaceOrderButton: {
    marginTop: 30,
    justifyContent: "center",
    alignItems: "center",
    height: 45,
    width: 135,
    borderWidth: 1,
    borderColor: "#000000",
    backgroundColor: "#C597FF",
    marginLeft: 120,
    borderRadius: 30,
    marginBottom: 40,
  },
  trashPlacement: {
    height: 33,
    width: 33,
    borderColor: "black",
    //borderWidth:1,
    backgroundColor: "red",
    borderRadius: 30,
    paddingLeft: 4,
    paddingTop: 2,
    position: "absolute",
    left: 330,
    top: 20,
  },
  TransactionCompleteOrderButton: {
    marginTop: 80,
    justifyContent: "center",
    alignItems: "center",
    height: 40,
    width: 120,
    borderWidth: 1,
    borderColor: "#000000",
    backgroundColor: "#C597FF",
    marginLeft: 135,
    borderRadius: 30,
    //marginBottom:"100%"
  },
});

export default styles;
